version: "3.8"

services:
  app:
    build: .
    container_name: app
    restart: always
    environment:
      - PORT=4000
    ports:
      - "4000:4000"
    links:
      - redis
    depends_on:
      - redis
    networks:
      - sergiodeusdedith_default
  redis:
    container_name: redis-cache
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - sergiodeusdedith_default

networks:
  sergiodeusdedith_default:
    external:
      name: sergiodeusdedith_default