version: "3.8"

services:
  esportes-api:
    build: .
    container_name: esportes-api
    restart: always
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - sergiodeusdedith_default

networks:
  sergiodeusdedith_default:
    external:
      name: sergiodeusdedith_default